### ISSUE TITLE
создать package.json

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/extra#2]
данный реп предпологает, что мы будем часто добавлять много пакетов, а комитить в 2 репа не очень удобно по мойму

**Comment by avmaisak** [comment]
Согласен в принципе. Но тогда надо разделить на категории. core | extra

**Comment by avmaisak** [comment]
не уверен. Теряется целостность. Предлагаю придерживаться текущей парадигмы. Когда наладится механизм по подгрузке метаданных из репозитория пакетов, преимущества будут налицо.

**Comment by makpif** [comment]
они и так подгружаються и это вполне налаженно. я предлагаю только не делать отдельный реп, чтоб проще добавлять пакеты было.

автоматизацию сдесь из за зависимостей делать - писать можно считать полноценный пакетный менеджер и думаю не стоит

**Comment by avmaisak** [comment]
я предполагал что эти данные будут здесь /Linux4Yourself.Book.Packages/tree/develop/src/packages/extra ...

**Comment by makpif** [comment]
а, засунуть их в реп с основными пакетами?

ну незнаю незнаю
